# Generated by Django 4.2.2 on 2023-06-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todumodel',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
