# Generated by Django 4.2.2 on 2023-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todu', '0003_alter_todumodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
